-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: May 10, 2016 at 02:58 AM
-- Server version: 5.5.39
-- PHP Version: 5.4.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `db_ci`
--

-- --------------------------------------------------------

--
-- Table structure for table `artikel`
--

CREATE TABLE IF NOT EXISTS `artikel` (
`id_artikel` int(11) NOT NULL,
  `judul` varchar(500) NOT NULL,
  `slug` varchar(128) NOT NULL,
  `ringkasan` text NOT NULL,
  `isi` text NOT NULL,
  `status_artikel` varchar(20) NOT NULL,
  `id_user` int(11) NOT NULL,
  `tanggal` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

--
-- Dumping data for table `artikel`
--

INSERT INTO `artikel` (`id_artikel`, `judul`, `slug`, `ringkasan`, `isi`, `status_artikel`, `id_user`, `tanggal`) VALUES
(1, 'Latihan Code Igniter', 'latihan-code-igniter', '<p>Quis nostrud exercitation ut enim ad minim veniam, eu fugiat nulla pariatur. Cupidatat non proident, consectetur adipisicing elit, mollit anim id est laborum. Ut labore et dolore magna aliqua.</p>', '<p>Quis nostrud exercitation ut enim ad minim veniam, eu fugiat nulla pariatur. Cupidatat non proident, consectetur adipisicing elit, mollit anim id est laborum. Ut labore et dolore magna aliqua.</p>\r\n<p>In reprehenderit in voluptate quis nostrud exercitation ut enim ad minim veniam. Sed do eiusmod tempor incididunt eu fugiat nulla pariatur. Sunt in culpa in reprehenderit in voluptate consectetur adipisicing elit.</p>\r\n<p>Velit esse cillum dolore ut enim ad minim veniam. Duis aute irure dolor ut aliquip ex ea commodo consequat. Eu fugiat nulla pariatur. Ut labore et dolore magna aliqua.</p>\r\n<p>Quis nostrud exercitation in reprehenderit in voluptate duis aute irure dolor. Ullamco laboris nisi sed do eiusmod tempor incididunt cupidatat non proident. Consectetur adipisicing elit, sunt in culpa mollit anim id est laborum. Ut aliquip ex ea commodo consequat.</p>\r\n<p>Velit esse cillum dolore qui officia deserunt lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ullamco laboris nisi. Velit esse cillum dolore eu fugiat nulla pariatur. Qui officia deserunt duis aute irure dolor lorem ipsum dolor sit amet. Sed do eiusmod tempor incididunt sunt in culpa cupidatat non proident.</p>', 'Publish', 1, '2016-03-13 08:01:06'),
(2, 'Menampilkan berita dengan CI', 'menampilkan-berita-dengan-ci', '<p>Cumque nihil impedit quo minus at vero eos et accusamus et iusto odio cum soluta nobis est eligendi optio. Id quod maxime placeat facere possimus, omnis dolor repellendus. Nisi ut aliquid ex ea commodi consequatur? Neque porro quisquam est, sed ut perspiciatis unde omnis cum soluta nobis est eligendi optio.</p>', '<p>Cumque nihil impedit quo minus at vero eos et accusamus et iusto odio cum soluta nobis est eligendi optio. Id quod maxime placeat facere possimus, omnis dolor repellendus. Nisi ut aliquid ex ea commodi consequatur? Neque porro quisquam est, sed ut perspiciatis unde omnis cum soluta nobis est eligendi optio.</p>\r\n<p>Sed quia non numquam eius modi iste natus error sit voluptatem quis autem vel eum iure reprehenderit. Saepe eveniet ut et voluptates repudiandae sint ullam corporis suscipit laboriosam, excepturi sint occaecati cupiditate non provident. Sed quia consequuntur magni dolores eos dicta sunt explicabo.</p>\r\n<p>Nisi ut aliquid ex ea commodi consequatur? Totam rem aperiam, omnis voluptas assumenda est, sed quia non numquam eius modi. Et quasi architecto beatae vitae dignissimos ducimus qui blanditiis qui in ea voluptate. Vel illum qui dolorem eum fugiat omnis voluptas assumenda est, quis autem vel eum iure reprehenderit.</p>\r\n<p>Ullam corporis suscipit laboriosam, id est laborum et dolorum fuga. Sed quia consequuntur magni dolores eos consequatur aut perferendis doloribus asperiores repellat. Sed quia non numquam eius modi quo voluptas nulla pariatur? Accusantium doloremque laudantium, omnis dolor repellendus. Et molestiae non recusandae.</p>\r\n<p>Atque corrupti quos dolores et quas molestias nam libero tempore, et expedita distinctio. Nisi ut aliquid ex ea commodi consequatur? Quo voluptas nulla pariatur? Id quod maxime placeat facere possimus, sed quia non numquam eius modi aut odit aut fugit. Tempora incidunt ut labore et dolore praesentium voluptatum deleniti excepturi sint occaecati cupiditate non provident.</p>', 'Publish', 1, '2016-03-13 08:01:57'),
(3, 'Latihan Halaman Statis dengan CI', 'latihan-halaman-statis-dengan-ci', '<p>Big is no longer impregnable to focus on improvement, not cost, as knowledge is fragmented into specialities. Building a dynamic relationship between the main players. Empowerment of all personnel, not just key operatives, the vitality of conceptual synergies is of supreme importance organizations capable of double-loop learning.</p>', '<p>Big is no longer impregnable to focus on improvement, not cost, as knowledge is fragmented into specialities. Building a dynamic relationship between the main players. Empowerment of all personnel, not just key operatives, the vitality of conceptual synergies is of supreme importance organizations capable of double-loop learning.</p>\r\n<p>Maximization of shareholder wealth through separation of ownership from management the three cs - customers, competition and change - have created a new world for business as knowledge is fragmented into specialities. In order to build a shared view of what can be improved, empowerment of all personnel, not just key operatives, through the adoption of a proactive stance, the astute manager can adopt a position at the vanguard. Building a dynamic relationship between the main players. Exploiting the productive lifecycle taking full cognizance of organizational learning parameters and principles, benchmarking against industry leaders, an essential process, should be a top priority at all times. Measure the process, not the people.</p>', 'Publish', 1, '2016-03-13 08:01:57'),
(4, 'Belajar CI Sendiri', 'belajar-ci-sendiri', '<p>In order to build a shared view of what can be improved, motivating participants and capturing their expectations, while those at the coal face don''t have sufficient view of the overall goals. Through the adoption of a proactive stance, the astute manager can adopt a position at the vanguard. To experience a profound paradigm shift, an important ingredient of business process reengineering the new golden rule gives enormous power to those individuals and units. Taking full cognizance of organizational learning parameters and principles, exploitation of core competencies as an essential enabler, organizations capable of double-loop learning.</p>', '<p>The strategic vision - if indeed there be one - is required to identify as knowledge is fragmented into specialities whenever single-loop learning strategies go wrong. From binary cause and effect to complex patterns, in a collaborative, forward-thinking venture brought together through the merging of like minds. That will indubitably lay the firm foundations for any leading company taking full cognizance of organizational learning parameters and principles, by moving executive focus from lag financial indicators to more actionable lead indicators. By adopting project appraisal through incremental cash flow analysis, building a dynamic relationship between the main players.</p>\r\n<p>In order to build a shared view of what can be improved, motivating participants and capturing their expectations, while those at the coal face don''t have sufficient view of the overall goals. Through the adoption of a proactive stance, the astute manager can adopt a position at the vanguard. To experience a profound paradigm shift, an important ingredient of business process reengineering the new golden rule gives enormous power to those individuals and units. Taking full cognizance of organizational learning parameters and principles, exploitation of core competencies as an essential enabler, organizations capable of double-loop learning.</p>\r\n<p>The strategic vision - if indeed there be one - is required to identify an investment program where cash flows exactly match shareholders'' preferred time patterns of consumption. Highly motivated participants contributing to a valued-added outcome. An important ingredient of business process reengineering the components and priorities for the change program motivating participants and capturing their expectations. The balanced scorecard, like the executive dashboard, is an essential tool whether the organization''s core competences are fully in line, given market realities benchmarking against industry leaders, an essential process, should be a top priority at all times.</p>', 'Publish', 1, '2016-03-13 08:01:28'),
(9, 'Cara Menampilkan Dashboard Admin pada web 1', 'cara-menampilkan-dashboard-admin-pada-web-1', 'Google Cardboard merupakan penemuan <a href="http://google.com/">Google</a> yang diumumkan pada saat acara Google I/O di California, 2014 lalu. Google Cardboard merupakan alat virtual reality yang menggunakan smartphone sebagai platform/layar.<br /> Google Cardboard ditujukan agar pengguna smartphones dapat merasakan Virtual Reality dengan cara yang mudah dan murah.', 'Google Cardboard merupakan penemuan <a href="http://google.com/">Google</a> yang diumumkan pada saat acara Google I/O di California, 2014 lalu. Google Cardboard merupakan alat virtual reality yang menggunakan smartphone sebagai platform/layar.</p>\r\n<p>Google Cardboard ditujukan agar pengguna smartphones dapat merasakan Virtual Reality dengan cara yang mudah dan murah.</p>\r\n<p>Contoh fungsinya antara lain:<br /> 1. Bermain game seakan-akan kita berada di dalam<br /> 2. Menonton video 3D seperti di bioskop<br /> 3. menonton video 360°<br /> 4. Keliling dunia dengan Google Earth</p>\r\n<p>Kelebihannya, apabila Anda menggerakkan kepala Anda ke kiri atau ke kanan, maka Anda juga bisa melihat kondisi sekitar dari aplikasi/permainan tersebut seperti nyata.</p>\r\n<p>Google Cardboard compatible dengan layar 4 – 5,7 inchi dan lebih optimal apabila mempunyai <em>gyroscopic sensor</em>. Selain perangkat android, perangkat apple khususnya iphone bisa menggunakan alat ini. Google Cardboard menggunakan lensa yang mempunyai titik fokus sangat pas sehingga tidak membahayakan mata. Apabila mata anda minus kurang dari 3, bisa lepas kacamata. Apabila lebih dari 3, bagian pinggir Google Cardboard perlu dipotong membentuk kacamata.</p>\r\n<p><strong> </strong></p>\r\n<p><strong>CARA KERJA :</strong></p>\r\n<p>Dengan cara menaruh smartphone di jarak yang pas dan bantuan lensa, lalu menggunakan aplikasi yang kompatibel,  lensa akan memberi efek 3D ketika di arahkan di mata anda. Anda bahkan bisa memutar/menggerakkan kepala anda untuk melihat sekitar, dengan bantuan Gyroscopic sensor di smartphone anda.</p>\r\n<p><strong>Merakit google cardboard.</strong></p>', 'Draft', 1, '2016-05-05 08:06:16'),
(11, 'Civil War', 'civil-war', 'afhjas hsajfhasfha sahflahfwehfa fsafajrf babfsa fksajfga fsafj abf sajfasfea agfkasfa', 'asfashfahsifhahfuag fsafhasfhya shfahsfh asfhasfhasklf h eugskdgkas gghah gagadsjk askjasdghagkjagle ashgdsiuhglk hguat7ewtge gasg djbg dkjgkusdg a giusdyga eth gyahtye8ygas gkjahge saguiehgl hkldsglehg ehgiughsghes ygeahgsahigesahgleah ghelghlseghaseugaeg e hashg eagheasgleasgesh glel glse glkehlaghaelgaesgeaeeaegh ae es hgaeksg h', 'Draft', 1, '2016-05-09 21:06:47'),
(12, 'menambah artikel', 'menambah-artikel', 'menambah artikel bagian 1', 'menambah artikel bagian 2 1', 'Draft', 1, '2016-05-10 00:38:51'),
(14, 'Captain America Civil War', 'captain-america-civil-war', '<p>"Captain America: Civil War" 2016 merupakan film aksi terbaik 2016. Film ini di sutradai oleh Anthony Russo dab Joe Russo, berdasarkan skenario yang di tulis oleh Christopher Markus dan Stephen McFeely.</p>', '<p>"Captain America: Civil War" 2016 merupakan film aksi terbaik 2016. Film ini di sutradai oleh Anthony Russo dab Joe Russo, berdasarkan skenario yang di tulis oleh Christopher Markus dan Stephen McFeely. Film hasil produksi Marvel Studios ini akan menyajikan adegan adegan yang sangat menegangkan dan seru pestinya. Rencananya Marvel akan merilis film America: Civil War pada tanggal 6 May 2016.<br /><br /></p>\r\n<div class="separator">&nbsp;</div>\r\n<div class="separator"><a href="http://3.bp.blogspot.com/-5Ub48TmF5Jg/ViOismm0gjI/AAAAAAAAAuk/ra1xygsGtBM/s1600/Captain-America.jpg"><img style="display: block; margin-left: auto; margin-right: auto;" title="Captain America: Civil War (2016)" src="http://3.bp.blogspot.com/-5Ub48TmF5Jg/ViOismm0gjI/AAAAAAAAAuk/ra1xygsGtBM/s320/Captain-America.jpg" alt="Captain America Civil War 2016" width="320" height="213" border="0" /></a></div>\r\n<p><br />Sederet tokoh super hero turut ambil bagian dari film ini, yaitu antara lain Steve Rogers (Captain America) , Robert Downey Jr. sebagai Tony Stark (Iron Man), Scarlet Johansson sebagai Natsha Romanoff(Black Widow), Sebastian Stan sebagai Bucky Barnes (Winter Soldier), Anthony Mackie sebagai Sam Wilson (Falcon), Paul Bettany sebagai The Vision, Jeremy Renner sebagai Clint Barton (Hawkeye) , Don Cheadle sebagai Jim Rhodes (War Machine), Elizabeth Olsen sebagai Wanda Maximoff (Scarlet Witch) dan Tom Holland sebagai Peter Parker&nbsp; (Spider-Man).</p>', 'Publish', 1, '2016-05-10 00:54:47'),
(15, 'Ada Apa Dengan Cinta 2', 'ada-apa-dengan-cinta-2', 'Ada Apa Dengan Cinta adalah salah satu film yang pernah booming pada tahun 2002.\r\n\r\nNicholas Saputra dan Dian Sastrowardoyo adalah 2 artis yang membintang Film tersebut dan menjadi ikon dari film Ada Apa Dengan Cinta ?.\r\n\r\nBerkat kesuksesan film itu, kedua artis tersebut juga semakin dikenal masyarakat. Skill akting dan alur cerita yang memang tepat dengan suasana anak remaja di tahun rillisnya, AADC menuai sukses yang luar biasa.', 'Ada Apa Dengan Cinta adalah salah satu film yang pernah booming pada tahun 2002.\r\n\r\nNicholas Saputra dan Dian Sastrowardoyo adalah 2 artis yang membintang Film tersebut dan menjadi ikon dari film Ada Apa Dengan Cinta ?.\r\n\r\nBerkat kesuksesan film itu, kedua artis tersebut juga semakin dikenal masyarakat. Skill akting dan alur cerita yang memang tepat dengan suasana anak remaja di tahun rillisnya, AADC menuai sukses yang luar biasa.\r\n‘\r\nBahkan soundtrack nya yang diisi oleh Melly Goeslaw, Eric dan Anda (Bunga) juga ikut sukses dan beberapa kali berada di puncak tangga lagu di banyak radio tanah air.\r\n\r\nMungkin jika anda yang pernah nonton film Ada Apa Dengan Cinta tahun 2002, ketika mendengar lagu Melly yang berjudul Denting dan lagu Anda (Bunga) yang berjudul Tentang Seseorang pasti akan teringat dengan kisah Rangga dan Cinta di AADC yang pertama.\r\n\r\nTahun 2016 ini, Film Ada Apa Dengan Cinta juga hadir dengan sekuel yang kedua AADC 2 (Ada Apa Dengan Cinta 2).\r\n\r\nAADC 2 masih dibintangi oleh artis yang sama dengan AADC tahun 2002, Dian Sastrowardoyo, Nicholas Saputra, Titi Kamal, Sissy Priscillia, Adinia Wirasti, Dennis Adhiswara, dan Mang Diman.\r\n\r\nHanya saja di AADC 2 ini tidak ada Ladya Cherill, yang di film AADC sebelumnya berperan sebagai ‘Alya’ karena tengah sibuk dengan pendidikannya.\r\n\r\nFilm AADC 2 disutradarai oleh Riri Riza dengan penulis skenario Mira Lesmana (Sekaligus Produser) dan Prima Rusdi.', 'Publish', 1, '2016-05-10 00:09:30'),
(16, 'Deadpool', 'deadpool', '<p>Saat mendengar kata superhero, Anda mungkin akan membayangkan sosok yang tak hanya kuat, tapi juga terlihat <em>cool</em>. Namun hal ini tampaknya tidak berlaku bagi <strong>Deadpool</strong>, tokoh yang disebut-sebut sebagai salah satu superhero paling <em>nyleneh</em> dari Marvel.</p>', '<p>Saat mendengar kata superhero, Anda mungkin akan membayangkan sosok yang tak hanya kuat, tapi juga terlihat <em>cool</em>. Namun hal ini tampaknya tidak berlaku bagi <strong>Deadpool</strong>, tokoh yang disebut-sebut sebagai salah satu superhero paling <em>nyleneh</em> dari Marvel.</p>\r\n<p>Film <a title="Deadpool Rilis Trailer Super Bowl, Tayang Di Bioskop Indonesia 10 Februari" href="http://sidomi.com/432966/deadpool-rilis-trailer-super-bowl-tayang-di-bioskop-indonesia-10-februari/">Deadpool </a>bercerita tentang <strong>Wade Wilson (Ryan Reynolds)</strong> yang merupakan seorang tentara militer. Kehidupan Wade awalnya cukup normal, ia bahkan memiliki seorang kekasih bernama<strong>Vanessa Carlysle (Morena Baccarin)</strong>. Namun suatu hari ia mendadak ambruk, dan belakangan diketahui kalau Wade ternyata mengidap kanker yang sulit disembuhkan.</p>\r\n<p>Wade pun sekarat, dan saat dirinya mulai putus asa, ia menyetujui sebuah tawaran menjadi kelinci percobaan dengan harapan penyakit kankernya bisa hilang. Ia pun meninggalkan Vanessa dan mulai menjadi objek eksperimen di sebuah laboratorium.</p>\r\n<p>Eksperimen tersebut rupanya gagal. Meski berhasil menghilangkan penyakit kanker yang diderita Wade, percobaan genetik ini ternyata membawa dampak lain. Tubuh Wade kini memiliki kemampuan menyembuhkan diri yang luar biasa cepat. Sayang, eksperimen tersebut juga membuat wajah dan kulitnya mengalami kerusakan.</p>\r\n<p>Wade pun kini memiliki kekuatan baru. Namun demi menuntaskan balas dendamnya pada orang-orang yang sudah menghancurkan hidupnya, Wade kemudian menciptakan alter ego bernama Deadpool.</p>\r\n<p>Deadpool sendiri dikenal sebagai karakter yang berada di &lsquo;zona abu-abu&rsquo;. Ia adalah anti-hero, seorang pembunuh bayaran namun masih memiliki kebaikan layaknya seorang superhero. Deadpool juga dikenal sebagai sosok yang nyentrik, tak kenal takut, dan kadang melakukan kekonyolan dengan selera humornya yang <em>nyleneh</em>.</p>\r\n<p>Film Deadpool kini sudah ditayangkan di seluruh bioskop Indonesia sejak tanggal 10 Februari 2016. Bila Anda penggemar film superhero, Deadpool tentunya tak boleh Anda lewatkan.</p>', 'Publish', 1, '2016-05-10 00:51:37');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `artikel`
--
ALTER TABLE `artikel`
 ADD PRIMARY KEY (`id_artikel`), ADD KEY `slug` (`slug`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `artikel`
--
ALTER TABLE `artikel`
MODIFY `id_artikel` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=17;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
